name: Build docker image

on:
  release:
    types: [published]
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      name:
        description: 'x-ray docker编译'
        required: true
        default: 'GitHub'

      

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: downcase REPO
        run: |
          echo "USERNAME=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Docker metadata v2fly flavor
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.USERNAME }}/nekoopenresty
          flavor: latest=auto
          tags: |
            type=sha
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push v2fly flavor
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: |
            linux/amd64
          provenance: false
          file: .github/docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          